services:
  web:
    container_name: web
    build: .
    ports:
      - "8000:8000"
    env_file:
      - ./.env

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

volumes:
  postgres_data:
