# Generated by Django 4.2.6 on 2023-10-14 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('size', models.CharField(choices=[('ti', 'Tiny'), ('sm', 'Small'), ('me', 'Medium'), ('la', 'Large')], default='ti', max_length=2)),
                ('friendliness', models.IntegerField(choices=[(1, 'Low'), (2, 'Low Medium'), (3, 'Medium'), (4, 'Medium High'), (5, 'High')])),
                ('trainability', models.IntegerField(choices=[(1, 'Low'), (2, 'Low Medium'), (3, 'Medium'), (4, 'Medium High'), (5, 'High')])),
                ('sheddigamount', models.IntegerField(choices=[(1, 'Low'), (2, 'Low Medium'), (3, 'Medium'), (4, 'Medium High'), (5, 'High')])),
                ('execirseneeds', models.IntegerField(choices=[(1, 'Low'), (2, 'Low Medium'), (3, 'Medium'), (4, 'Medium High'), (5, 'High')])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('ma', 'Male'), ('fe', 'Female')], default='ma')),
                ('color', models.CharField(max_length=10)),
                ('favorite_food', models.CharField(max_length=20)),
                ('favorite_toy', models.CharField(max_length=20)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.breed')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
