# Generated by Django 4.2.6 on 2023-10-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='size',
            field=models.CharField(choices=[('ti', 'Tiny'), ('sm', 'Small'), ('me', 'Medium'), ('la', 'Large')], max_length=2),
        ),
        migrations.AlterField(
            model_name='dog',
            name='gender',
            field=models.CharField(choices=[('ma', 'Male'), ('fe', 'Female')]),
        ),
    ]
